# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'
inhibit_all_warnings!

target 'GliKitSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GliKitSwift', :path => '../GliKitSwift'
  pod "PromiseKit", "~> 6.8"

  # Pods for GliKitSwiftDemo

  target 'GliKitSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GliKitSwiftDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
    end
end
