# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'
inhibit_all_warnings!

target 'GliKitSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GliKitSwift', :path => '../GliKitSwift'

  # Pods for GliKitSwiftDemo

  target 'GliKitSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GliKitSwiftDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
