# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!

target 'GliKitSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.0.1'
  pod 'Kingfisher', '~> 5.15.6'
  pod 'Alamofire', '~> 5.2.2'

end
